import { Migration } from '../common/interfaces/migration.interface';

/**
 * Converts tenancy identifiers (tenantId, organisationId) on every table, and questions.categoryId,
 * from UUID to VARCHAR(255), so these externally issued IDs no longer have to be UUIDs
 * (e.g. "tenant-acme", "org-42", "cat-maths").
 *
 * IDs generated by this service (testId, attemptId, questionId, sectionId, ...) stay UUID.
 * Existing values are preserved via `USING "<col>"::text` (canonical lowercase UUID text), and indexes on
 * these columns (e.g. idx_questions_tenant, idx_tests_tenant, idx_test_attempts_user,
 * idx_ai_feedback_job_attempt) are rebuilt automatically by Postgres. None of these columns has a
 * foreign key or default value.
 *
 * The statement is idempotent: columns that do not exist or are no longer UUID are skipped.
 * Note: ALTER COLUMN TYPE rewrites each table under an ACCESS EXCLUSIVE lock; run it in a maintenance window.
 */
const TENANCY_TABLES = [
  'tests',
  'testSections',
  'testQuestions',
  'testRules',
  'testAttempts',
  'testUserAnswers',
  'questions',
  'questionOptions',
  'optionQuestions',
  'questionPools',
  'attemptQuestions',
  'testUserAnswerAIFeedbackJobs',
  'testAttemptsReval',
  'testUserStatus',
];

const IDENTIFIER_COLUMNS: Array<[string, string]> = [
  ...TENANCY_TABLES.flatMap((table): Array<[string, string]> => [
    [table, 'tenantId'],
    [table, 'organisationId'],
  ]),
  ['questions', 'categoryId'],
];

const targetsSql = IDENTIFIER_COLUMNS.map(([table, column]) => `('${table}', '${column}')`).join(',\n        ');

export class TenancyAndCategoryIdsUuidToVarchar005 implements Migration {
  version = '005';
  name = 'tenancy_and_category_ids_uuid_to_varchar';
  description = 'Change tenantId, organisationId and questions.categoryId columns from UUID to VARCHAR(255)';
  dependencies = ['004'];

  async up(connection: any): Promise<void> {
    await connection.query(`
      DO $$
      DECLARE
        target RECORD;
      BEGIN
        FOR target IN
          SELECT c.table_name, c.column_name
          FROM information_schema.columns c
          JOIN (VALUES
        ${targetsSql}
          ) AS t(table_name, column_name)
            ON c.table_name = t.table_name AND c.column_name = t.column_name
          WHERE c.table_schema = current_schema()
            AND c.data_type = 'uuid'
        LOOP
          EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN %I TYPE VARCHAR(255) USING %I::text',
            target.table_name, target.column_name, target.column_name
          );
        END LOOP;
      END $$;
    `);
  }

  /**
   * Reverts to UUID. Fails (and changes nothing) if any non-UUID value has been stored since `up` ran.
   */
  async down(connection: any): Promise<void> {
    await connection.query(`
      DO $$
      DECLARE
        target RECORD;
        invalid_count BIGINT;
      BEGIN
        FOR target IN
          SELECT c.table_name, c.column_name
          FROM information_schema.columns c
          JOIN (VALUES
        ${targetsSql}
          ) AS t(table_name, column_name)
            ON c.table_name = t.table_name AND c.column_name = t.column_name
          WHERE c.table_schema = current_schema()
            AND c.data_type = 'character varying'
        LOOP
          EXECUTE format(
            'SELECT count(*) FROM %I WHERE %I IS NOT NULL AND %I !~* ''^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$''',
            target.table_name, target.column_name, target.column_name
          ) INTO invalid_count;

          IF invalid_count > 0 THEN
            RAISE EXCEPTION 'Cannot revert %.%: % row(s) contain non-UUID values', target.table_name, target.column_name, invalid_count;
          END IF;

          EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN %I TYPE UUID USING %I::uuid',
            target.table_name, target.column_name, target.column_name
          );
        END LOOP;
      END $$;
    `);
  }
}
